01/04/b2024 03:19:27 PM Selenium Manager binary found at: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager
01/04/2024 03:19:27 PM Executing process: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --output json
01/04/2024 03:19:27 PM chromedriver not found in PATH
01/04/2024 03:19:27 PM chrome detected at /usr/bin/google-chrome
01/04/2024 03:19:27 PM Running command: /usr/bin/google-chrome --version
01/04/2024 03:19:27 PM Output: "Google Chrome 115.0.5790.102 "
01/04/2024 03:19:27 PM Detected browser: chrome 115.0.5790.102
01/04/2024 03:19:27 PM Discovering versions from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
01/04/2024 03:19:27 PM Required driver: chromedriver 115.0.5790.170
01/04/2024 03:19:27 PM chromedriver 115.0.5790.170 already in the cache
01/04/2024 03:19:27 PM Driver path: /home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver
01/04/2024 03:19:27 PM Browser path: /usr/bin/google-chrome
01/04/2024 03:19:27 PM Using driver at: /home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver
01/04/2024 03:19:28 PM Started executable: `/home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver` in a child process with pid: 310810
01/04/2024 03:19:28 PM POST http://localhost:50229/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "browserVersion": null, "goog:chromeOptions": {"prefs": {"profile.default_content_settings.popups": 0, "download.default_directory": "/home/administrator/cbs_bag_hold/data", "directory_upgrade": true}, "extensions": [], "binary": "/usr/bin/google-chrome", "args": ["--headless=new"]}}}}
01/04/2024 03:19:28 PM Starting new HTTP connection (1): localhost:50229
01/04/2024 03:19:28 PM http://localhost:50229 "POST /session HTTP/1.1" 200 0
01/04/2024 03:19:28 PM Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"115.0.5790.102","chrome":{"chromedriverVersion":"115.0.5790.170 (cc0d30c2ca5577520c8646671513241faa0bc105-refs/branch-heads/5790@{#1923})","userDataDir":"/tmp/.org.chromium.Chromium.ZKMXfc"},"goog:chromeOptions":{"debuggerAddress":"localhost:34991"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"02788bcd1ce3038d660830a4aa9c018f"}} | headers=HTTPHeaderDict({'Content-Length': '828', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
01/04/2024 03:19:28 PM Finished Request
01/04/2024 03:19:36 PM Invalid HTTP_HOST header: '10.244.18.104:8000'. You may need to add '10.244.18.104' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '10.244.18.104:8000'. You may need to add '10.244.18.104' to ALLOWED_HOSTS.
01/04/2024 03:19:36 PM Bad Request: /login
01/04/2024 03:19:36 PM Invalid HTTP_HOST header: '10.244.18.104:8000'. You may need to add '10.244.18.104' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '10.244.18.104:8000'. You may need to add '10.244.18.104' to ALLOWED_HOSTS.
01/04/2024 03:19:36 PM Bad Request: /favicon.ico
01/04/2024 03:20:22 PM /home/flipkart/bagtrac/bagtracproject/settings.py changed, reloading.
01/04/2024 03:20:23 PM Selenium Manager binary found at: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager
01/04/2024 03:20:23 PM Executing process: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --output json
01/04/2024 03:20:23 PM chromedriver not found in PATH
01/04/2024 03:20:23 PM chrome detected at /usr/bin/google-chrome
01/04/2024 03:20:23 PM Running command: /usr/bin/google-chrome --version
01/04/2024 03:20:23 PM Output: "Google Chrome 115.0.5790.102 "
01/04/2024 03:20:23 PM Detected browser: chrome 115.0.5790.102
01/04/2024 03:20:23 PM Required driver: chromedriver 115.0.5790.170
01/04/2024 03:20:23 PM chromedriver 115.0.5790.170 already in the cache
01/04/2024 03:20:23 PM Driver path: /home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver
01/04/2024 03:20:23 PM Browser path: /usr/bin/google-chrome
01/04/2024 03:20:23 PM Using driver at: /home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver
01/04/2024 03:20:23 PM Started executable: `/home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver` in a child process with pid: 311002
01/04/2024 03:20:24 PM POST http://localhost:50233/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "browserVersion": null, "goog:chromeOptions": {"prefs": {"profile.default_content_settings.popups": 0, "download.default_directory": "/home/administrator/cbs_bag_hold/data", "directory_upgrade": true}, "extensions": [], "binary": "/usr/bin/google-chrome", "args": ["--headless=new"]}}}}
01/04/2024 03:20:24 PM Starting new HTTP connection (1): localhost:50233
01/04/2024 03:20:24 PM http://localhost:50233 "POST /session HTTP/1.1" 200 0
01/04/2024 03:20:24 PM Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"115.0.5790.102","chrome":{"chromedriverVersion":"115.0.5790.170 (cc0d30c2ca5577520c8646671513241faa0bc105-refs/branch-heads/5790@{#1923})","userDataDir":"/tmp/.org.chromium.Chromium.JtNXgK"},"goog:chromeOptions":{"debuggerAddress":"localhost:40943"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"7e68ac21b6f6e273e59ff577ba20ad83"}} | headers=HTTPHeaderDict({'Content-Length': '828', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
01/04/2024 03:20:24 PM Finished Request
01/04/2024 03:21:10 PM Not Found: /favicon.ico
01/04/2024 03:23:25 PM Internal Server Error: /download_all_data
Traceback (most recent call last):
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view bagtrac.views.download_all_data didn't return an HttpResponse object. It returned None instead.
01/04/2024 03:23:47 PM Internal Server Error: /add_bnr
Traceback (most recent call last):
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'bagtrac.bagtrac_bnrbag' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/flipkart/bagtrac/bagtrac/views.py", line 428, in add_bnr_bags
    BNRBag.objects.create(bag=bnr)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/flipkart/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/flipkart/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'bagtrac.bagtrac_bnrbag' doesn't exist")
01/04/2024 03:24:15 PM Selenium Manager binary found at: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager
01/04/2024 03:24:15 PM Executing process: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --output json
01/04/2024 03:24:15 PM chromedriver not found in PATH
01/04/2024 03:24:15 PM chrome detected at /usr/bin/google-chrome
01/04/2024 03:24:15 PM Running command: /usr/bin/google-chrome --version
01/04/2024 03:24:15 PM Output: "Google Chrome 115.0.5790.102 "
01/04/2024 03:24:15 PM Detected browser: chrome 115.0.5790.102
01/04/2024 03:24:15 PM Required driver: chromedriver 115.0.5790.170
01/04/2024 03:24:15 PM chromedriver 115.0.5790.170 already in the cache
01/04/2024 03:24:15 PM Driver path: /home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver
01/04/2024 03:24:15 PM Browser path: /usr/bin/google-chrome
01/04/2024 03:24:15 PM Using driver at: /home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver
01/04/2024 03:24:15 PM Started executable: `/home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver` in a child process with pid: 311437
01/04/2024 03:24:15 PM POST http://localhost:47929/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "browserVersion": null, "goog:chromeOptions": {"prefs": {"profile.default_content_settings.popups": 0, "download.default_directory": "/home/administrator/cbs_bag_hold/data", "directory_upgrade": true}, "extensions": [], "binary": "/usr/bin/google-chrome", "args": ["--headless=new"]}}}}
01/04/2024 03:24:15 PM Starting new HTTP connection (1): localhost:47929
01/04/2024 03:24:15 PM http://localhost:47929 "POST /session HTTP/1.1" 200 0
01/04/2024 03:24:15 PM Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"115.0.5790.102","chrome":{"chromedriverVersion":"115.0.5790.170 (cc0d30c2ca5577520c8646671513241faa0bc105-refs/branch-heads/5790@{#1923})","userDataDir":"/tmp/.org.chromium.Chromium.nFEmiB"},"goog:chromeOptions":{"debuggerAddress":"localhost:44959"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"304e287079edcc5917b0cdec6028e65e"}} | headers=HTTPHeaderDict({'Content-Length': '828', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
01/04/2024 03:24:15 PM Finished Request
01/04/2024 03:24:21 PM Selenium Manager binary found at: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager
01/04/2024 03:24:21 PM Executing process: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --output json
01/04/2024 03:24:21 PM chromedriver not found in PATH
01/04/2024 03:24:21 PM chrome detected at /usr/bin/google-chrome
01/04/2024 03:24:21 PM Running command: /usr/bin/google-chrome --version
01/04/2024 03:24:21 PM Output: "Google Chrome 115.0.5790.102 "
01/04/2024 03:24:21 PM Detected browser: chrome 115.0.5790.102
01/04/2024 03:24:21 PM Required driver: chromedriver 115.0.5790.170
01/04/2024 03:24:21 PM chromedriver 115.0.5790.170 already in the cache
01/04/2024 03:24:21 PM Driver path: /home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver
01/04/2024 03:24:21 PM Browser path: /usr/bin/google-chrome
01/04/2024 03:24:21 PM Using driver at: /home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver
01/04/2024 03:24:21 PM Started executable: `/home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver` in a child process with pid: 311564
01/04/2024 03:24:21 PM POST http://localhost:33185/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "browserVersion": null, "goog:chromeOptions": {"prefs": {"profile.default_content_settings.popups": 0, "download.default_directory": "/home/administrator/cbs_bag_hold/data", "directory_upgrade": true}, "extensions": [], "binary": "/usr/bin/google-chrome", "args": ["--headless=new"]}}}}
01/04/2024 03:24:21 PM Starting new HTTP connection (1): localhost:33185
01/04/2024 03:24:21 PM http://localhost:33185 "POST /session HTTP/1.1" 200 0
01/04/2024 03:24:21 PM Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"115.0.5790.102","chrome":{"chromedriverVersion":"115.0.5790.170 (cc0d30c2ca5577520c8646671513241faa0bc105-refs/branch-heads/5790@{#1923})","userDataDir":"/tmp/.org.chromium.Chromium.VKkBeb"},"goog:chromeOptions":{"debuggerAddress":"localhost:42949"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"ac6d878f758752daf5f8528e8f56dd93"}} | headers=HTTPHeaderDict({'Content-Length': '828', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
01/04/2024 03:24:21 PM Finished Request
01/04/2024 03:24:28 PM Selenium Manager binary found at: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager
01/04/2024 03:24:28 PM Executing process: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --output json
01/04/2024 03:24:28 PM chromedriver not found in PATH
01/04/2024 03:24:28 PM chrome detected at /usr/bin/google-chrome
01/04/2024 03:24:28 PM Running command: /usr/bin/google-chrome --version
01/04/2024 03:24:28 PM Output: "Google Chrome 115.0.5790.102 "
01/04/2024 03:24:28 PM Detected browser: chrome 115.0.5790.102
01/04/2024 03:24:28 PM Required driver: chromedriver 115.0.5790.170
01/04/2024 03:24:28 PM chromedriver 115.0.5790.170 already in the cache
01/04/2024 03:24:28 PM Driver path: /home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver
01/04/2024 03:24:28 PM Browser path: /usr/bin/google-chrome
01/04/2024 03:24:28 PM Using driver at: /home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver
01/04/2024 03:24:28 PM Started executable: `/home/flipkart/.cache/selenium/chromedriver/linux64/115.0.5790.170/chromedriver` in a child process with pid: 311701
01/04/2024 03:24:29 PM POST http://localhost:41537/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "browserVersion": null, "goog:chromeOptions": {"prefs": {"profile.default_content_settings.popups": 0, "download.default_directory": "/home/administrator/cbs_bag_hold/data", "directory_upgrade": true}, "extensions": [], "binary": "/usr/bin/google-chrome", "args": ["--headless=new"]}}}}
01/04/2024 03:24:29 PM Starting new HTTP connection (1): localhost:41537
01/04/2024 03:24:29 PM http://localhost:41537 "POST /session HTTP/1.1" 200 0
01/04/2024 03:24:29 PM Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"115.0.5790.102","chrome":{"chromedriverVersion":"115.0.5790.170 (cc0d30c2ca5577520c8646671513241faa0bc105-refs/branch-heads/5790@{#1923})","userDataDir":"/tmp/.org.chromium.Chromium.YI4U0w"},"goog:chromeOptions":{"debuggerAddress":"localhost:45353"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"fcf1bdc467fd7a166e17ccdb96e9413a"}} | headers=HTTPHeaderDict({'Content-Length': '828', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
01/04/2024 03:24:29 PM Finished Request
